#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xe8e9fb26, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xce8ddf91, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xfdffe514, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xa6a69673, __VMLINUX_SYMBOL_STR(drop_nlink) },
	{ 0x1d84b6bf, __VMLINUX_SYMBOL_STR(mark_buffer_dirty_inode) },
	{ 0x22e1ae6f, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0xfdc3345c, __VMLINUX_SYMBOL_STR(__bread) },
	{ 0x9577a5e0, __VMLINUX_SYMBOL_STR(unload_nls) },
	{ 0xba827703, __VMLINUX_SYMBOL_STR(make_bad_inode) },
	{ 0x5fc56a46, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x4c51cb3b, __VMLINUX_SYMBOL_STR(generic_file_llseek) },
	{ 0x99771715, __VMLINUX_SYMBOL_STR(__mark_inode_dirty) },
	{ 0xdf793584, __VMLINUX_SYMBOL_STR(inode_permission) },
	{ 0x67c2fa54, __VMLINUX_SYMBOL_STR(__copy_to_user) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xf5b4a948, __VMLINUX_SYMBOL_STR(crc_itu_t) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0xb1eaed89, __VMLINUX_SYMBOL_STR(simple_write_end) },
	{ 0x815b5dd4, __VMLINUX_SYMBOL_STR(match_octal) },
	{ 0x34184afe, __VMLINUX_SYMBOL_STR(current_kernel_time) },
	{ 0xa4e205d0, __VMLINUX_SYMBOL_STR(block_write_begin) },
	{ 0x9f523f3c, __VMLINUX_SYMBOL_STR(seq_puts) },
	{ 0x5245104b, __VMLINUX_SYMBOL_STR(is_bad_inode) },
	{ 0x27d7bdbb, __VMLINUX_SYMBOL_STR(pagecache_get_page) },
	{ 0xca97bf18, __VMLINUX_SYMBOL_STR(generic_file_open) },
	{ 0xb5198b77, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0xf6ba7124, __VMLINUX_SYMBOL_STR(__lock_page) },
	{ 0x2b1c6df1, __VMLINUX_SYMBOL_STR(ll_rw_block) },
	{ 0x9aab66b5, __VMLINUX_SYMBOL_STR(__lock_buffer) },
	{ 0xf7802486, __VMLINUX_SYMBOL_STR(__aeabi_uidivmod) },
	{ 0xb5876a40, __VMLINUX_SYMBOL_STR(generic_file_aio_read) },
	{ 0xd3f57a2, __VMLINUX_SYMBOL_STR(_find_next_bit_le) },
	{ 0x9c956a0f, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x353e3fa5, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0xde87307c, __VMLINUX_SYMBOL_STR(inc_nlink) },
	{ 0x65692de9, __VMLINUX_SYMBOL_STR(__generic_file_aio_write) },
	{ 0xa0b061f1, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x98df4c44, __VMLINUX_SYMBOL_STR(mount_bdev) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0x355f2c86, __VMLINUX_SYMBOL_STR(generic_read_dir) },
	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
	{ 0x32ddd5b6, __VMLINUX_SYMBOL_STR(call_rcu) },
	{ 0x5a5bc5c1, __VMLINUX_SYMBOL_STR(unlock_buffer) },
	{ 0xa32ac603, __VMLINUX_SYMBOL_STR(truncate_setsize) },
	{ 0x455293f6, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x4504f0b2, __VMLINUX_SYMBOL_STR(__insert_inode_hash) },
	{ 0xd0ccc1ac, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0x94f67bdb, __VMLINUX_SYMBOL_STR(mpage_readpages) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x29aaeb95, __VMLINUX_SYMBOL_STR(mpage_readpage) },
	{        0, __VMLINUX_SYMBOL_STR(inode_add_bytes) },
	{        0, __VMLINUX_SYMBOL_STR(current_fs_time) },
	{ 0x10b45503, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x2a48efeb, __VMLINUX_SYMBOL_STR(d_obtain_alias) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xdfd61436, __VMLINUX_SYMBOL_STR(_raw_write_unlock) },
	{ 0x4bc9fa80, __VMLINUX_SYMBOL_STR(_raw_read_unlock) },
	{ 0x2965fa40, __VMLINUX_SYMBOL_STR(kunmap) },
	{ 0x52c5d0f, __VMLINUX_SYMBOL_STR(mpage_writepages) },
	{ 0x328a05f1, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x84b183ae, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0x1de930f2, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xf6c545b5, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x90b4afbb, __VMLINUX_SYMBOL_STR(set_nlink) },
	{ 0xc986f47d, __VMLINUX_SYMBOL_STR(__wait_on_buffer) },
	{ 0xd100acbd, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0x6ccf527f, __VMLINUX_SYMBOL_STR(setattr_copy) },
	{ 0x21a87705, __VMLINUX_SYMBOL_STR(sync_dirty_buffer) },
	{ 0x63742abf, __VMLINUX_SYMBOL_STR(truncate_pagecache) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0x9fb46a6c, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0x83211609, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xa958ed4, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0xafe8e991, __VMLINUX_SYMBOL_STR(__brelse) },
	{ 0xfe5d4bb2, __VMLINUX_SYMBOL_STR(sys_tz) },
	{ 0xe4b163b7, __VMLINUX_SYMBOL_STR(inode_init_once) },
	{ 0x5388adc5, __VMLINUX_SYMBOL_STR(page_follow_link_light) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0xb5ff1a73, __VMLINUX_SYMBOL_STR(invalidate_inode_buffers) },
	{ 0x40a9b349, __VMLINUX_SYMBOL_STR(vzalloc) },
	{ 0xfe4e8bab, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xbc10dd97, __VMLINUX_SYMBOL_STR(__put_user_4) },
	{ 0xd2be16cc, __VMLINUX_SYMBOL_STR(generic_file_mmap) },
	{ 0x279961d, __VMLINUX_SYMBOL_STR(kmap) },
	{ 0xac0dd15f, __VMLINUX_SYMBOL_STR(block_write_full_page) },
	{ 0x622db0e0, __VMLINUX_SYMBOL_STR(inode_sub_bytes) },
	{ 0x58e0e1a, __VMLINUX_SYMBOL_STR(load_nls) },
	{ 0xa4d08474, __VMLINUX_SYMBOL_STR(generic_write_end) },
	{        0, __VMLINUX_SYMBOL_STR(do_sync_read) },
	{ 0xd3fd4dd2, __VMLINUX_SYMBOL_STR(unlock_new_inode) },
	{ 0xb6a9ed8e, __VMLINUX_SYMBOL_STR(kill_block_super) },
	{ 0xf08d2c53, __VMLINUX_SYMBOL_STR(inode_change_ok) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xfc807937, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{        0, __VMLINUX_SYMBOL_STR(d_tmpfile) },
	{ 0x82a51796, __VMLINUX_SYMBOL_STR(register_filesystem) },
	{ 0x6f0d7ca7, __VMLINUX_SYMBOL_STR(iput) },
	{ 0x7bf32d83, __VMLINUX_SYMBOL_STR(generic_file_fsync) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xa7641add, __VMLINUX_SYMBOL_STR(do_sync_write) },
	{ 0x3ad9ee5d, __VMLINUX_SYMBOL_STR(ihold) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xadacf225, __VMLINUX_SYMBOL_STR(load_nls_default) },
	{ 0x3d3fa67d, __VMLINUX_SYMBOL_STR(d_splice_alias) },
	{ 0xa4258586, __VMLINUX_SYMBOL_STR(block_truncate_page) },
	{ 0xb08671f3, __VMLINUX_SYMBOL_STR(sb_set_blocksize) },
	{ 0x5e0e4cab, __VMLINUX_SYMBOL_STR(generic_readlink) },
	{ 0xe93a67c8, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0xbbcde1b9, __VMLINUX_SYMBOL_STR(d_make_root) },
	{ 0xce985c4f, __VMLINUX_SYMBOL_STR(__blockdev_direct_IO) },
	{ 0x4cbbd171, __VMLINUX_SYMBOL_STR(__bitmap_weight) },
	{ 0x47e9626c, __VMLINUX_SYMBOL_STR(mark_buffer_dirty) },
	{ 0xed4ddbf3, __VMLINUX_SYMBOL_STR(ioctl_by_bdev) },
	{ 0x5910d34b, __VMLINUX_SYMBOL_STR(unregister_filesystem) },
	{ 0xe52ad340, __VMLINUX_SYMBOL_STR(init_special_inode) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0x703f41fb, __VMLINUX_SYMBOL_STR(new_inode) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x99bb8806, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0xe0476a1, __VMLINUX_SYMBOL_STR(generic_file_splice_read) },
	{ 0x85954e8f, __VMLINUX_SYMBOL_STR(__getblk) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0xa67d1e2d, __VMLINUX_SYMBOL_STR(grab_cache_page_write_begin) },
	{ 0x7bf31b72, __VMLINUX_SYMBOL_STR(clear_inode) },
	{ 0x70f5d33f, __VMLINUX_SYMBOL_STR(page_put_link) },
	{ 0xc2caeb7f, __VMLINUX_SYMBOL_STR(d_instantiate) },
	{ 0x7d4e2276, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0x8d2d65be, __VMLINUX_SYMBOL_STR(flush_dcache_page) },
	{ 0xada39853, __VMLINUX_SYMBOL_STR(generic_block_bmap) },
	{ 0xab46a2f6, __VMLINUX_SYMBOL_STR(clear_nlink) },
	{ 0x837c0a6e, __VMLINUX_SYMBOL_STR(iget_locked) },
	{ 0x4dec6038, __VMLINUX_SYMBOL_STR(memscan) },
	{        0, __VMLINUX_SYMBOL_STR(vfs_fsync_range) },
	{ 0x47f9602e, __VMLINUX_SYMBOL_STR(inode_init_owner) },
	{ 0x81f1c4ec, __VMLINUX_SYMBOL_STR(truncate_inode_pages) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=crc-itu-t";


MODULE_INFO(srcversion, "93A9449B056A32A1193CD83");
